### ISSUE TITLE
failing build

### ISSUE THREAD

**Issue by mro** [Megalithicirelandmap/Megalithicirelandmap.github.io#3]
follow up from https://github.com/Megalithicirelandmap/Megalithicirelandmap.github.io/issues/2#issuecomment-235278597

Let's see if we can quickly find out what's going on.

The [failing build has in line 138](https://travis-ci.org/Megalithicirelandmap/Megalithicirelandmap.github.io/builds/147426203#L138) a message saying:

> monuments.gpx:2794: element sym: Relax-NG validity error : Element sym has extra content: text

If we look into [monuments.gpx:2794 (as it was when the build failed)](https://github.com/Megalithicirelandmap/Megalithicirelandmap.github.io/blob/a9c23181c8406a319daba27ac5d08a15d80235bb/monuments.gpx#L2794), we see:

> ```
> <sym>subject#Church</sym>
> ```

which I guess fails, because I constrained `<sym>` to consist of lowercase letters only, because later down the drain (when displayed on the map) it's treated case-sensitive, so `Church` is something different as `church` is.

I'll quickly try the fix, wait a second…

**Comment by mro** [comment]
looks good.

We may alternatively constrain the values used in `<sym>` to the ones declared in [index.html](https://github.com/Megalithicirelandmap/Megalithicirelandmap.github.io/blob/f7d3fecd5ec4cefd1aea0818b3278253a0f88973/index.html#L80) – that's the actual dependency. But then we need to edit the validation process each time you introduce a new icon. So I stuck to a plausbility check requiring lowercase letters.

**Comment by mro** [comment]
@Megalithicireland just poking.

**Comment by Megalithicireland** [comment]
Thanks Marcus.
I did so many edits. I was changing lowercase to upper in a lot of the titles(Bubble) and adding church to a lot of syms. I was probably in repetitive mode. My apologies for missing that error. sorry for disturbing you.

**Comment by mro** [comment]
nevermind, don't feel bad, humans err. That's why I have the machine check the edits.
